version: '3'
services:
    mysql_db:
        image: mysql:8
        ports:
            - 3306:3306
        networks:
            - filestorage-network
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=sanketlathiya
            - MYSQL_DATABASE=filestoragedb
    filestorage_api:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        networks:
            - filestorage-network
        depends_on:
            - mysql_db
networks:
    filestorage-network:
        driver: bridge